# Generated by Django 4.2.27 on 2025-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Скільки грамів цього продукту замовили', verbose_name='Вага (г)'),
            preserve_default=False,
        ),
    ]
