# Generated by Django 4.2.27 on 2026-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='weight',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_snapshot',
            field=models.CharField(blank=True, help_text='Наприклад: 300 г або 160 мл', max_length=20, null=True, verbose_name='Вага / обʼєм'),
        ),
    ]
