# Generated by Django 4.2.26 on 2025-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cheese', 'Сири'), ('jam', 'Джеми'), ('juice', 'Соки')], default='cheese', max_length=20),
        ),
    ]
