# Generated by Django 4.2.27 on 2025-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Вводити тільки цифри, наприклад: 250', null=True, verbose_name='Вага (г)'),
        ),
    ]
