# Generated by Django 4.2.27 on 2026-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Наприклад: 300 г або 160 мл', max_length=20, null=True, verbose_name='Вага / обʼєм'),
        ),
    ]
